require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - spec/**/*.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 125

Metrics/AbcSize:
  Enabled: false
