require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
#    - codebreaker.gemspec
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
