require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: disable
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Enabled: false
