require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - codebreaker.gemspec
    - spec/**/*.rb